import { Dimensions, Platform } from 'react-native';

const Constants = {
    //fonts
    FONT_SIZE_SMALL:10,
    FONT_SIZE__MEDIUM:12,
    FONT_SIZE_LARGE:14,
    FONT_SIZE_EXTRA_LARGE:16,

   //colors
    COLOR_GREEN_PROFILE:"rgba(96, 176, 115,1)",
    COLOR_PRIMARY:"rgba(98,180,108,1)",
    COLOR_GREEN:"rgba(131,189,85,1)",
    COLOR_GREEN_LIGHT:"rgba(189,223,162,1)",
    COLOR_GREEN_DARK:"rgba(47,100,58,1)",
    COLOR_ORANGE:"rgba(241,144,15,1)",
    COLOR_WHITE:"rgba(255,255,255,1)",
    COLOR_BLACK:"rgba(112,121,128,1)",
    COLOR_BLACK_LIGHT:"rgba(181,181,181,1)",
    COLOR_GREY:"rgba(240,240,240,1)",
    COLOR_GREY_DARK:"rgba(112,120,122,1)",
    COLOR_GREY_LIGHT:"rgba(172,172,172,1)",
    COLOR_GREY_SHADED:"rgba(64,64,64,0.7)",
    COLOR_RED:"rgba(237,36,22,1)",
    COLOR_FOOTER_GREY:"rgba(112,121,128,1)",

    //button
    SEND_OTP:'send otp',
    CANCEL:'cancel',
    SUBMIT:'submit',
    VERIFY:'verify',
    BACK:'back',
    OK:'ok',
    ACCEPT:'accept',
    SEND:"send",
    PICKEDUP:"picked up",
    YES:"yes",
    NO:"no",
    Next:'next',
    Proceed:'proceed',
    
    //Label
    CurrentTrip:'current trips',
    Date:'date',
    ForgotPassword:'Forgot Password?',
    Nyc_Syc:'Nyc-Syc',
    ViewYOurTripDetail:'view your trip details',
    Message:'message',
    RateYourTrip:'Rate your Trip',
    LabelYourTrip:'Label your Trip',
    ReviewYourTrip:'Review your Trip',
    PartnerName:"Partner's Name",
    Telephonenumber:'Telephone Number',
    DateOfPickUp:'Date of Pick up',
    PickUpTime:'Pick up Time',
    DropUpTime:'drop up time',
    ArrivalTime:'Arrival Time',
    PickUpLocation:'Pick up Location',
    frequency:'Frequency',
    DestinationLocation:'Destination Location',
    CostOfTruckingService:'Cost of Trucking Service',
    CargoType:'Cargo Type',
    CargoHandling:'Cargo Handling',
    CargoHandlingCharges:'Cargo Handling Charges',
    CostOfRecurring:'Cost of Recurring',
    RecurringRequirement:'Recurring Requirement',
    Status:'Status',
    ReviewSentSuccessfully:'Review Sent Successfully.',
    MobileNumber:'Mobile Number',
    Password:'Password',
    SignIn:'SIGN IN',
    RequestSentSuccessfully:'request sent successfully.',
    SupportSubject:'support subject',
    NotAMemmberYet:'Not a Member yet?',
    truckingwarehouse:'trucking + warehouse',
    TruckBooking:'truck bookings',
    WarehouseService:'warehouse services',
    Trip:"trip",
    CollectMyLoad:'collect my load',
    TotalBookings:'total bookings',
    UpcomingTrip:'Upcoming trips',
    ViewAll:'view all',
    CurrentStatus:"Current Status",
    EstimatedTimetonextstatus:'Estimated time to next Status Update',
    EstimatedTimeTocmpleteTrip:'Estimated time to Completion of trip',
    EstimatedDateTocmpleteTrip:'Estimated Date for Completion of trip',
    DriverName:'Driver Name',
    ContactNo:'Contact No',
    PartnerName:'Partner Name',
    LiveGeoPin:"Live Geo Pin",

};


export default Constants;